version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_container
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
    ports:
      - ${SERVER_PORT:-3001}:3001
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: bash -c "npm install && nodemon --watch . --legacy-watch server.ts"

volumes:
  postgres_data:
